app:
  port: 8080

users:
  cy:
    name: Cy
    picture: ./cpotify.svg
    key: password
    mediaRoot: "./Unlike Pluto"
    cache: on
  cy2:
    name: Cy 2
    picture: ./cpotify.svg
    key: password
    mediaRoot: "./media"
    cache: off