app:
  port: 5000

users:
  cy:
    name: Cy
    picture: ./profileImgs/1.jpg
    key: password
    mediaRoot: "./Unlike Pluto"
    cache: on
  cy2:
    name: Cy 2
    picture: ./profileImgs/2.jpg
    key: password
    mediaRoot: "./media"
    cache: off
  ytdl:
    name: Cy 3
    mediaRoot: "C:/Users/cyfin/Music/ytdl spotify songs 21JUN2021 2"
    picture: ./profileImgs/2.jpg
    key: password
    cache: off